[2023-03-15T18:16:45.434+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 01_dag_test.read_from_db manual__2023-03-15T18:16:43.482811+00:00 [queued]>
[2023-03-15T18:16:45.441+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 01_dag_test.read_from_db manual__2023-03-15T18:16:43.482811+00:00 [queued]>
[2023-03-15T18:16:45.441+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T18:16:45.442+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-15T18:16:45.445+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T18:16:45.454+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): read_from_db> on 2023-03-15 18:16:43.482811+00:00
[2023-03-15T18:16:45.460+0000] {standard_task_runner.py:55} INFO - Started process 8010 to run task
[2023-03-15T18:16:45.466+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '01_dag_test', 'read_from_db', 'manual__2023-03-15T18:16:43.482811+00:00', '--job-id', '1171', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpemcgmhte']
[2023-03-15T18:16:45.469+0000] {standard_task_runner.py:83} INFO - Job 1171: Subtask read_from_db
[2023-03-15T18:16:45.542+0000] {task_command.py:376} INFO - Running <TaskInstance: 01_dag_test.read_from_db manual__2023-03-15T18:16:43.482811+00:00 [running]> on host f11e2626d663
[2023-03-15T18:16:45.608+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=01_dag_test
AIRFLOW_CTX_TASK_ID=read_from_db
AIRFLOW_CTX_EXECUTION_DATE=2023-03-15T18:16:43.482811+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-15T18:16:43.482811+00:00
[2023-03-15T18:16:45.622+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-03-15T18:16:45.630+0000] {sql.py:315} INFO - Running statement: SELECT * FROM pg_catalog.pg_tables;, parameters: None
[2023-03-15T18:16:45.633+0000] {sql.py:324} INFO - Rows affected: 108
[2023-03-15T18:16:45.646+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=01_dag_test, task_id=read_from_db, execution_date=20230315T181643, start_date=20230315T181645, end_date=20230315T181645
[2023-03-15T18:16:45.676+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-03-15T18:16:45.699+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
